# Generated by Django 4.2.7 on 2024-02-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_finepage_elec_finepage_fash_finepage_homefurt'),
    ]

    operations = [
        migrations.AddField(
            model_name='finepage',
            name='boook',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
