# Generated by Django 4.2.7 on 2024-02-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_finepage_boook'),
    ]

    operations = [
        migrations.AddField(
            model_name='finepage',
            name='groseries',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
